---
config:
  theme: neutral
---

flowchart LR

subgraph Actors
Resident([Resident])
Admin([System Admin])
Mailpit([Mailpit Web UI])
end

subgraph System["DigiBank System (GUI + Backend API)"]
UC_Login((Login + TOTP MFA))
UC_ViewDashboard((View Dashboard))
UC_FetchBills((Fetch Gov Bills))
UC_PayFiat((Pay Bill - FIAT))
UC_PayCrypto((Pay Bill - BTC/ETH/STABLE))
UC_Transfer((Transfer Money))

UC_HomeToggle((Toggle Home Device))
UC_Thermostat((Set Thermostat))

UC_AdminUsers((Admin: Users CRUD/Search))
UC_AdminTx((Admin: Transactions CRUD/Search))
UC_Export((Admin: Export to txt/))
UC_Metrics((Admin: View Metrics Snapshot))
UC_Forecast((Admin: View Forecast))

UC_TxReportDownload((Admin: Download Transactions XLSX/PDF))
UC_TxReportEmail((Admin: Email Transactions Report SMTP))
end

Resident --> UC_Login
Resident --> UC_ViewDashboard
Resident --> UC_FetchBills
Resident --> UC_PayFiat
Resident --> UC_PayCrypto
Resident --> UC_Transfer
Resident --> UC_HomeToggle
Resident --> UC_Thermostat

Admin --> UC_Login
Admin --> UC_AdminUsers
Admin --> UC_AdminTx
Admin --> UC_Export
Admin --> UC_Metrics
Admin --> UC_Forecast
Admin --> UC_TxReportDownload
Admin --> UC_TxReportEmail

UC_TxReportEmail --> Mailpit
