---
config:
  theme: neutral
---
erDiagram

    %% Kullanıcı (In-Memory Prototype Model)
    USERS {
        bigint id PK
        string username
        string password_hash
        string totp_secret
        string role "ADMIN, RESIDENT"
        decimal fiat_balance
        decimal crypto_balance
    }

    %% Bankacılık Modülü
    TRANSACTIONS {
        bigint id PK
        bigint user_id FK
        string description
        string bank_code
        string address
        decimal amount
        datetime record_date
        string status "BASARILI, BASARISIZ"
    }

    USERS ||--o{ TRANSACTIONS : "initiates"

    %% Akıllı Şehir Modülü
    SENSORS {
        bigint id PK
        string type "TRAFFIC, LIGHT, SMOKE"
        string location_code
        string status "ACTIVE, MAINTENANCE"
        decimal last_value
    }

    SENSOR_EVENTS {
        bigint id PK
        bigint sensor_id FK
        datetime timestamp
        string event_type
        decimal value
        string severity "INFO, WARNING, CRITICAL"
    }

    CITY_ROUTINES {
        int id PK
        string name
        string trigger_condition
        string action_command
    }

    SENSORS ||--o{ SENSOR_EVENTS : "generates"
    
    %% Audit ve Loglama
    AUDIT_LOGS {
        bigint id PK
        bigint user_id FK
        string action
        string entity_affected
        datetime timestamp
        string ip_address
    }

    USERS ||--o{ AUDIT_LOGS : "performs"
